version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.4-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
        name: Update bundler
        command: gem update bundler
      - run:
        name: Which bundler?
        command: bundle -v
      - restore_cache:
        keys:
          - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          - gem-cache-v1-{{ arch }}-{{ .Branch }}
          - gem-cache-v1
      - run: bundle install --path vendor/bundle
      - run: bundle clean
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rspec